name: Build

on:
  release:
    types:
      - released


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
          uses: actions/setup-node@v2
          with:
            node-version: 14.x
      - name: Npm install
        run: npm install
      - name: Build & Publish
        run: npm build && npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
